```{r}
library(httr)
library(tidyverse)
library(ggplot2)
library(jsonlite)
```

```{r}
url <- "https://api-football-v1.p.rapidapi.com/v3/trophies"
queryString <- list(player = "276") 
api_key <- Sys.getenv("FOOTBALL_API")
response <- VERB("GET", url, query = queryString, add_headers('X-RapidAPI-Key' = api_key, 
'X-RapidAPI-Host' = 'api-football-v1.p.rapidapi.com'), content_type("application/octet-stream"))

raw_data <- content(response, "text")
parsed <- fromJSON(raw_data)
df <- parsed$response
df
```
```{r}
Sys.getenv("FOOTBALL_API")
```



```{r}
# Creating a function of the capacities of the venues by country

GetBiggestVenues <- function(country_name, top){
  
  # Obtaining the venue data of the specifiec country
  url <- "https://api-football-v1.p.rapidapi.com/v3/venues"
  queryString <- list(country = country_name) # Set the country name parameter
  response <- VERB("GET", url, query = queryString, add_headers('X-RapidAPI-Key' = api_key, 
  'X-RapidAPI-Host' = 'api-football-v1.p.rapidapi.com'), content_type("application/octet-stream"))
  
  raw_data <- content(response, "text")
  parsed <- fromJSON(raw_data)
  
  # Extract the data frame
  df <- parsed$response
  
  # Sort data frame in descending order
  df <- df %>% 
    arrange(desc(capacity)) %>% 
    slice(1:top)
  
  top_venue_bar <- ggplot(df, aes(x=reorder(name, capacity), y=capacity)) +
    geom_bar(stat='identity', fill = "navy") +
    labs(title = "Capacity of Venues", y="Capacity (persons)", x="Venue Names") +
    coord_flip()
  top_venue_bar # Display the bar chart 
  
}

GetBiggestVenues("England", 10)
```


```{r}
# Extract some key info of coaches

GetCoachInfo <- function(team_id){
  
  url <- "https://api-football-v1.p.rapidapi.com/v3/coachs"
  queryString <- list(team = team_id) # Set the country name parameter
  response <- VERB("GET", url, query = queryString, add_headers('X-RapidAPI-Key' = api_key, 
  'X-RapidAPI-Host' = 'api-football-v1.p.rapidapi.com'), content_type("application/octet-stream"))
  
  raw_data <- content(response, "text")
  parsed <- fromJSON(raw_data)
  
  # Extract the data frame
  df <- parsed$response
  
  # Unnesting birth and team, then selecting name, age, nationality, birth info and team names
  df <- df %>% 
    unnest(birth, names_sep="_") %>% 
    unnest(team, names_sep="_") %>% 
    select(firstname, lastname, age, birth_date, birth_place, birth_country, nationality, team_name)
  df # Display the data frame
    
}

GetCoachInfo("33")
```

```{r}
# Input two players and comapres the number of trophies they earned
CompareTrophies <- function(player_id.1, player_id.2){
  
  url <- "https://api-football-v1.p.rapidapi.com/v3/trophies"
  
  # Obtaining the data of player 1
  queryString1 <- list(player = player_id.1) 
  response1 <- VERB("GET", url, query = queryString1, add_headers('X-RapidAPI-Key' = api_key, 
  'X-RapidAPI-Host' = 'api-football-v1.p.rapidapi.com'), content_type("application/octet-stream"))
  raw_data1 <- content(response1, "text")
  parsed1 <- fromJSON(raw_data1)
  df1 <- parsed1$response
  
  # Obtaining the data of player 2
  queryString2 <- list(player = player_id.2) 
  response2 <- VERB("GET", url, query = queryString2, add_headers('X-RapidAPI-Key' = api_key, 
  'X-RapidAPI-Host' = 'api-football-v1.p.rapidapi.com'), content_type("application/octet-stream"))
  raw_data2 <- content(response2, "text")
  parsed2 <- fromJSON(raw_data2)
  df2 <- parsed2$response
  
  # Create a data frame of the two players
  trophy <- data.frame(
    player_id = c(player_id.1, player_id.2), 
    n_trophy = c(nrow(df1), nrow(df2))
  )
  
  # Compare the lengths of player 1 to player 2
  if (nrow(df1) > nrow(df2)){
    # If player 1 has more trophies than player 2
    cat("Player", player_id.1, "has", nrow(df1) - nrow(df2), "more trophies than player", player_id.2)
    
    bigger_bar <- ggplot(trophy, aes(x=reorder(player_id, n_trophy, FUN = desc), y=n_trophy)) +
      geom_col(fill = "green") +
      labs(title = "Number of Trophies Won by Player", x = "Player ID", y = "Number of Trophies")
    bigger_bar
    
    # If player 1 has equal amount of trophies as player 2
  } else if (nrow(df1) == nrow(df2)){
    cat("Both player", player_id.1, "and player", player_id.2, "have", nrow(df1), "trophies")
    
    same_bar <- ggplot(trophy, aes(x=player_id, y=n_trophy)) + 
      geom_col(fill="grey") +
      labs(title = "Number of Trophies Won by Player", x = "Player ID", y = "Number of Trophies")
    same_bar
    
    # If player 1 has less trophies than player 2
  } else {
    cat("Player", player_id.1, "has", nrow(df2) - nrow(df1), "less trophies than player", player_id.2)
    
    smaller_bar <- ggplot(trophy, aes(x=reorder(player_id, n_trophy), y=n_trophy)) +
      geom_col(fill = "red") + 
      labs(title = "Number of Trophies Won by Player", x = "Player ID", y = "Number of Trophies")
    smaller_bar
  }
}

CompareTrophies("230", "276")
```


