# name: R Package Tests
# on: [push]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     container: docker://dvcorg/cml:latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Install system dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libcurl4-openssl-dev libssl-dev libxml2-dev

#       - name: Cache Renv dependencies
#         uses: actions/cache@v2
#         with:
#           path: ${{ runner.temp }}/renv/cache
#           key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-renv-

#       - name: Setup R
#         uses: r-lib/actions/setup-r@v2

#       - name: Restore Renv project
#         run: |
#           R -e 'install.packages("renv")'
#           R -e 'renv::restore()'

#       - name: Run tests
#         run: |
#           R -e 'testthat::test_dir("tests")'
