name: R Package Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Renv dependencies
        uses: actions/cache@v2
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0' 

      - name: Restore Renv project
        run: |
          R -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")'
          R -e 'renv::restore()'

      - name: Run tests
        run: |
          R -e 'testthat::test_dir("tests")'
